steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - bash: |
      # Check if verbose mode needs to be turned on
      CMD=""
      CMD="$CMD DEBUG=cypress:*"
      cd /home/vsts/work/1/s/

      npm i
      ls
      VERIFY_CMD="$CMD ./node_modules/.bin/cypress verify"
      RUN_CMD="$CMD ./node_modules/.bin/cypress run --browser ${{ parameters.browserType }}"

      # Check if Cypress record information is provided
      if [ ! -z "$CYPRESS_RECORD_KEY" ]
      then
        # Record key was set
        RUN_CMD="$RUN_CMD --record --parallel --group \"${{ parameters.browserType }}\" --ci-build-id $BUILDID"
      fi
      eval $VERIFY_CMD
      eval $RUN_CMD
    displayName: 'Run the cypress tests'