steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - bash: |
      # Check if verbose mode needs to be turned on
      CMD=""
      CMD="$CMD DEBUG=cypress:*"
      echo "hello"
      ls
      echo "Install project dependencies"
      npm i
      RUN_CMD="$CMD cypress run --browser ${{ parameters.browserType }}"
      eval $RUN_CMD
    displayName: 'Run the cypress tests'
