steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - task: Cache@2
    displayName: 'Cache npm'
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      restoreKeys: |
        npm | "$(Agent.OS)"
        npm
      path: $(npm_config_cache)

  - script: |
      npm ci
    displayName: 'Install project dependencies'
    
  - bash: |
      # Check if verbose mode needs to be turned on
      CMD=""
      CMD="$CMD DEBUG=cypress:*"
      echo "hello"
      ls
      echo "Install project dependencies"
      npm i
      RUN_CMD="$CMD cypress run --browser ${{ parameters.browserType }}"
      eval $RUN_CMD
    displayName: 'Run the cypress tests'
