steps:
  - task: NodeTool@0
    displayName: 'Use Node 12.x'
    inputs:
      versionSpec: 12.x

  - bash: |
      # Check if verbose mode needs to be turned on
      CMD=""
      CMD="$CMD DEBUG=cypress:*"
      echo "hello"
      ls
      echo "Install project dependencies"
      npm i
      VERIFY_CMD="$CMD ./node_modules/.bin/cypress verify"
      RUN_CMD="$CMD ./node_modules/.bin/cypress run --browser ${{ parameters.browserType }}"
      eval $VERIFY_CMD
      eval $RUN_CMD
    displayName: 'Run the cypress tests'
