name: 'Cypress E2E Testing'

trigger:
  - master

variables:
  - name: npm_config_cache
    value: $(Pipeline.Workspace)/.npm
  - name: CYPRESS_CACHE_FOLDER # Overrides the default cache location
    value: $(Pipeline.Workspace)/.cache/Cypress

stages:
  - stage: e2e_testing_stage_chrome
    displayName: 'Chrome E2E Testing'
    jobs:
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E in Chrome'
        pool:
          vmImage: macos-latest
        steps:
          - template: devops/e2e.testing.yml
            parameters:
              browserType: chrome