name: 'Cypress E2E Testing'

trigger:
  - master

stages:
  - stage: e2e_testing_stage_chrome
    displayName: 'Chrome E2E Testing'
    jobs:
      - job: e2e_testing_job_chrome
        displayName: 'Run E2E in Chrome'
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: devops/e2e.testing.yml
            parameters:
              browserType: chrome